spring.application.name=api-gateway
server.port=8080

# JWT CONFIG
jwt.secret=parasbramhankarinojri1234456abcdefghijklmnopqrstuvwxyz


# EUREKA CONFIGURATION
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.hostname=localhost



# ---------- GATEWAY ROUTES ----------

# AUTH SERVICE
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**
# auth-service endpoints are public
#spring.cloud.gateway.routes[0].filters[0]=JwtAuthenticationFilter


# QUESTION SERVICE
spring.cloud.gateway.routes[1].id=question-service
spring.cloud.gateway.routes[1].uri=lb://QUESTION-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/questions/**
spring.cloud.gateway.routes[1].filters[0]=JwtAuthenticationFilter


# QUIZ SERVICE
spring.cloud.gateway.routes[2].id=quiz-service
spring.cloud.gateway.routes[2].uri=lb://QUIZ-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/quiz/**
spring.cloud.gateway.routes[2].filters[0]=JwtAuthenticationFilter


# LOAD BALANCER
spring.cloud.loadbalancer.enabled=true

# GATEWAY LOGGING (Optional)
#logging.level.org.springframework.cloud.gateway=DEBUG